### numpy를 쓰면 리스트를 행렬로 바꿀 수 있어 2차원, 3차원 데이터를 만들 수 있다.

In [ ]:
import numpy as np

In [ ]:
a.reshape(10,10)

In [ ]:
좌표 = (
    ["aa1", "ab1", "ac1"],
    ["aa2", "ab2", "ac2"],
    ["aa3", "ab3", "ac3"],
    ["aa4", "ab4", "ac4"],
)



In [ ]:
좌표

In [ ]:
좌표[2][2]

In [ ]:
%timeit (좌표[2][2])

In [ ]:
a

In [ ]:
a =a.reshape(10,10)

In [ ]:
a

In [ ]:
a[ : , [0,2]]

In [ ]:
a [ :5 , :6]

In [ ]:
a = np.arange(4)
print(a.dtype)

In [ ]:
a = np.arange(6).reshape(3,2)
print(a.ndim)

In [ ]:
a.reshape(1,6)

### [[   ]]1차원으로 되돌리니까 아직 2차원으로보임

In [ ]:
a.flatten()

In [ ]:
a.reshape(-1)

Q. 학생들의 점수를 ndarray로 표현하라.

문자열을 제외하고 점수만 표현
  
<img src="https://i.ibb.co/Rcsc9d2/numpy-5.png" width="250" style="float:left" />

In [ ]:
arr = [30, 25, 66, 23, 44, 23]
a = np.array(arr).reshape(2,3)
a


점수들의 합을 출력하라

In [ ]:
sum(a[1])

In [ ]:
a[1].sum()

In [ ]:
a.sum(axis=0)

In [ ]:
a.sum(axis=1)

In [ ]:
a.sum(axis=1)[1]

Q. 학생들의 점수를 ndarray로 표현하라.

문자열을 제외하고 점수만 표현
  
<img src="https://i.ibb.co/Rcsc9d2/numpy-5.png" width="250" style="float:left" />

In [ ]:
a[ : , 1 ].mean()

## 다항식 풀기

사람과 강아지의 수는 총 4입니다. 다리의 개수는 14입니다. 사람과 강아지의 수는?  
사람의 수를 x, 강아지의 수를 y로 정의하자.

$ x + y = 4 $  
$ 2x + 4y = 14 $

In [ ]:
import numpy as np
a = np.array([
    [1,1],
    [2,4]
])

b = np.array([4,14])

In [ ]:
inv_a = np.linalg.inv(a)

In [ ]:
inv_a @ b

In [ ]:
inv_a

In [ ]:
print(b)

linspace는 구간을 입력된 개수로 분할

0부터 5까지를 50개의 구간으로 분할하는 코드

In [ ]:
np.linspace(0,10,3)

In [ ]:
x = np. arange(10)
y = x**2

In [ ]:
import matplotlib.pyplot as plt

plt.plot( x, y)

In [ ]:
import matplotlib.pyplot as plt

x = np.linspace(0, 1 , 100)
y = x**2



plt.plot( x, y)

In [ ]:
import matplotlib.pyplot as plt

x = np.linspace(0, 1 , 100)
x = y**2



plt.plot( x, y)

지도에 써먹을라면?

In [ ]:
좌표x = int(input())
좌표y = int(input())
x = np. arange(좌표x)
y = np. arange(좌표y)


In [ ]:
x

In [ ]:
import numpy as np
a = np. arange(4)
print(a.dtype)
print(a)

In [ ]:
a = a.astype('int8')
print(a.dtype)
a[0] = 127
a[1] = 128  # 요게 이상해짐
print(a)

In [ ]:
a = np.arange(4)
print(a)
print( a * 3 )

In [ ]:
a = np.arange(4)
b = np.arange(2,6)
print(a+b)

In [ ]:
a = np.arange(4)
b = np.arange(2,67) # 같은 범위여야한다!
print(a+b)

### 분산, 표준편차도 구할 수 있음

In [96]:
a = np.arange(4)
a[  : 2 ]

array([0, 1])

In [98]:
a[0]

0

In [99]:
a[0] =3
a

array([3, 1, 2, 3])

In [100]:
a[[0,3]]=0

In [101]:
a

array([0, 1, 2, 0])

## 오 그럼 원하는 좌표에 내용 넣을수도 있겠다!

In [116]:
지도 = np.arange(100)
지도 = 지도.reshape(10,10)

좌표x = int(input()) - 1
좌표y = int(input()) - 1

넣을값 = int(input())

지도[좌표x, 좌표y] = 넣을값

print(지도)

[[    0     1     2     3     4     5     6     7     8     9]
 [   10    11    12    13    14    15    16    17    18    19]
 [   20    21    22    23    24    25    26    27    28    29]
 [   30    31    32    33    34    35    36    37    38    39]
 [   40    41    42    43    44    45    46    47    48    49]
 [   50    51    52    53    54    55    56    57    58    59]
 [   60    61    62    63    64    65    66    67    68    69]
 [   70    71    72    73    74    75    76 10000    78    79]
 [   80    81    82    83    84    85    86    87    88    89]
 [   90    91    92    93    94    95    96    97    98    99]]


Q. LG 전자의 주가가 85000원 이하로 떨어진 횟수는?

In [118]:
lge = np.array([93000, 82400, 99100, 81000, 72300])

In [119]:
len( lge[    lge<85000  ])


3

Q. 종가가 80000원 이상  90000원 미만인 값을 출력하라

In [120]:
cond1 = lge >= 80000
cond2 = lge < 90000

In [123]:
lge [ cond1 & cond2] # 두 개가 모두 참인 걸 표현 &

array([82400, 81000])

In [124]:
lge[ ~ cond1 ]

array([72300])

지도에 사진 올려놓는 툴! pip install opencv-python