# 넘파이 (Numpy)
수학 및 과학 연산을 위한 파이썬 패키지입니다. 
- 기술통계 분석 정도에 사용
- matplotlib, Pandas 등 다른 Python 모듈과 함께 사용

홈페이지 : https://numpy.org/devdocs/user/quickstart.html

참고자료 : https://wikidocs.net/160667

파이썬 모듈을 사용하기 위해서는 import를 해야 합니다.  
많은 사람들이 import 하는 방식을 사용하는 것이 가독성을 높일 수 있습니다.

In [22]:
import numpy as np

## NdArray

넘파이에서는 배열을 효과적으로 관리하기 위한 ndarray 객체를 제공합니다. 이는 파이썬 기본 자료구조인 리스트 (튜플)을 <b>업그레이드</b> 해서 보다 향상된 기능을 제공합니다. 리스트를 상속받아 더 많은 기능을 구현해서 사용성을 높이는 것으로 추측해 볼 수 있죠?

In [23]:
arr = [1, 2, 3, 4]
a = np.array(arr)
print( type (a) )

<class 'numpy.ndarray'>


리스트를 업그레이드 했기 때문에 리스트가 제공하는 모든 기능을 사용할 수 있습니다. 인덱싱, 슬라이싱도 정상동작함을 확인할 수 있습니다.

1
4
[2, 3]


`zeros` 함수를 사용하면 0으로 채워진 `ndarray`를 만들 수 있습니다. 

[0. 0. 0.]


`ones` 함수를 사용하면 1로 채워진 `ndarray`를 만들 수 있습니다. 

[1. 1. 1.]


튜플로 x, y 크기를 지정하면 2차원 형태로 배열이 생성됩니다. 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


이차원 데이터가 저장된 리스트도 한 번에 ndarray로 변환할 수 있습니다.   
리스트에 저장된 다음 값은 `arr = [[1, 2], [3, 4]]` 아래 그림과 같은 구조를 표현합니다. 

<img src="https://i.ibb.co/6g96V6V/numpy-0.png" width="300" style="float:left" />

In [6]:
arr = [[1, 2], [3, 4]]





[[1 2]
 [3 4]]


`vstack` 함수는 두 개의 `ndarray`를 `vertical` 방향으로 합칩니다. 이 때 전달하는 `ndarray`는 리스트로 정의해서 파라미터로 전달해야 합니다. 

[[1 2]
 [3 4]]


`hstack` 함수는 두 개의 `ndarray`를 `horizontal` 방향으로 합칩니다.

[1 2 3 4]


reshape은 차원을 재정의 합니다. 

In [7]:
arr = [1, 2, 3, 4]





[[1 2]
 [3 4]]


넘파이의 `arange()` 함수는 `range()` 함수와 유사하게 호출할 수 있으며, 결괏값으로 `ndarray`를 반환합니다. 

In [8]:
a = np.arange(4)
print(a)



[0 1 2 3]
[0 2 4 6 8]


시작/끝/증감폭을 지정할 수 있습니다.

다음 2차원 `ndarray`에는 총 3개의 데이터가 있습니다. 
```
[  데이터1 
   데이터2
   데이터3 ]
```
그리고 각각의 데이터에는 다시 `ndarray`가 들어 있습니다.

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## NdArray의 인덱싱과 슬라이싱

0번째 들어있는 데이터를 인덱싱으로 출력하면 `ndarray`가 출력됩니다. 

In [12]:
print(a[0])

[0 1 2]


<img src="https://i.ibb.co/hcYQ0sn/numpy-1.png" width="300" style="float:left" />

하나의 값을 출력하려면 또 다시 인덱싱을 사용하면 되겠죠? 첫 번째 행의 두 번째 열에 있는 값 (`1`)을 출력해 봅시다.

<img src="https://i.ibb.co/MNMwS45/numpy-2.png" width="300" style="float:left" />

슬라이싱으로 0번, 1번 두 개의 줄을 선택하기 

<img src="https://i.ibb.co/zmKXhbY/numpy-3.png" width="300" style="float:left" />

불연속적인 행 선택하기

0번 1번 행과 0번 1번 열을 선택하기

<img src="https://i.ibb.co/N7dnqtj/numpy-4.png" width="300" style="float:left" />

불연속적인 행출력하기

불연속적인 열출력하기

## Numpy의 다양한 속성값

In [17]:
a = np.arange(4)
print(a.dtype)

int32


`shape` 속성은 데이터의 크기를 출력합니다. 

이차원 데이터에서도 정상동작 합니다. 

In [19]:
a = np.arange(6).reshape(3, 2)
print(a.shape)

(3, 2)


In [22]:
a = np.arange(6).reshape(3, 2)
print(a.ndim)

2


`reshape`으로 다시 1차원으로 변경할 수 있습니다.

`flat` 속성과 형변환을 통해 1차원으로 변경할 수도 있습니다.

Q. 학생들의 점수를 ndarray로 표현하라.
- 문자열을 제외하고 점수만 표현

<img src="https://i.ibb.co/Rcsc9d2/numpy-5.png" width="250" style="float:left" />

Q. 기말고사 점수의 합을 출력하라.
- `sum()` 함수 사용

<img src="image/6.png" width="250" style="float:left" />

Q. 영어점수의 평균을 출력하라.

<img src="image/7.png" width="250" style="float:left" />

축 정보 axis 

###### 3차원데이터

## reshape 메서드의 이해

같은 메모리를 공유하며 보여지는 결과만 다른 다른 뷰 (view) 사용합니다. 

In [3]:
a = np.arange(9)
id(a)

1537299995344

In [4]:
b = a.reshape(3, 3)
id(b)

1537300507504

`base` 속성에는 원본 데이터의 위치가 기록돼 있습니다. 

1537299995344

`a`의 값을 변경한 뒤에 `b`의 값을 확인해 봅시다. 

복사본을 만들고 싶다면 `copy`를 사용합니다.

얕은 복사 (shallow copy)와 깊은 복사 (deep copy)

`is`와 `==`

## numpy와 함수  및 메서드
numpy는 수치연산과 관련된 다양한 함수를 제공합니다. 

`random.randn(숫자)` 메서드는 `0`부터 `숫자 - 1` 범위의 임의의 수를 반환합니다. 

In [3]:
num = np.random.randint(5)
print(num)

3


시작값과 끝값을 지정할 수도 있습니다. 

2

세 번째 파라미터는 size를 튜플로 지정합니다.  
- `size=(행, 열)`

`random.shuffle(ndarray)`은 ndarray의 데이터의 순서를 무작위로 변경합니다.  
- `shuffle` 메서드는 값을 반환하지 않고 파라미터 자체를 변경합니다. 

`chioce` 메서드는 데이터를 sampling 합니다. 
- `np.random.choice(a, size=None, replace=True, p=None)`
- a는 1차원 데이터

`np.unique` 메서드는 중복된 값을 제거합니다.

`linspace`는 구간을 입력된 개수로 분할합니다.
- 0부터 5까지를 50개의 구간으로 분할하는 코드

In [23]:
np.linspace(0, 5, 50)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

회전 

## 다항식 풀기

사람과 강아지의 수는 총 4입니다. 다리의 개수는 14입니다. 사람과 강아지의 수는?  
사람의 수를 x, 강아지의 수를 y로 정의하자.

$ x + y = 4 $  
$ 2x + 4y = 14 $

행렬식으로 표현해 봅시다.

In [3]:
import numpy as np

a = np.array( [
    [1, 1],
    [2, 4]
])

b = np.array([4, 14])

`solve` 를 사용한 해결

역행렬을 사용한 해결